description: >
  The executor called "default"

parameters:
  tag:
    default: current
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string

docker:
  - image: 'cimg/base:<<parameters.tag>>'
