version: 2.1
description: |
    My test orb is a Hello World example.
commands:
    greet:
        description: |
            Example of usage of the orb's job or of the job's greet command in a step.
        parameters:
            to:
                default: World
                description: Hello to whom?
                type: string
        steps:
            - run:
                command: |
                    #!/bin/bash
                    # This example uses envsubst to support variable substitution in the string parameter type.
                    # https://circleci.com/docs/orbs-best-practices/#accepting-parameters-as-strings-or-environment-variables
                    TO=$(circleci env subst "${PARAM_TO}")
                    # If for any reason the TO variable is not set, default to "World"
                    echo "Hello ${TO:-World}!"
                environment:
                    PARAM_TO: <<parameters.to>>
                name: Hello Greeting Command
executors:
    default:
        description: |
            The executor called "default"
        docker:
            - image: cimg/base:<<parameters.tag>>
        parameters:
            tag:
                default: current
                description: |
                    Pick a specific cimg/node image variant: https://hub.docker.com/r/cimg/node/tags
                type: string
jobs:
    hello:
        description: |
            Job is responsible for greeting.
        executor: default
        parameters:
            to:
                default: World
                description: Hello to whom?
                type: string
        steps:
            - greet:
                to: << parameters.to >>
examples:
    example:
        description: |
            Sample example description.
        usage:
            version: "2.1"
            orbs:
                mergisheim: krepon/mergisgheim@1.2.3
            jobs:
                my_job_using_command:
                    docker:
                        - image: alpine:latest
                    steps:
                        - mergisheim/greet: null
                          to: FrodoBaggins
            workflows:
                use-my-orb-job:
                    jobs:
                        - mergisheim/greet
                        - my_job_using_command

