commands:
    greet:
        description: |
            This command echos "Hello World" using file inclusion.
        parameters:
            to:
                default: World
                description: Hello to whom?
                type: string
        steps:
            - run:
                command: \<<include(scripts/greet.sh)>>
                environment:
                    PARAM_TO: <<parameters.to>>
                name: Hello Greeting
description: |
    My test orb is a Hello World example.
examples:
    example:
        description: |
            Sample example description.
        usage:
            orbs:
                <orb-name>: <namespace>/<orb-name>@1.2.3
            version: 2.1
            workflows:
                use-my-orb:
                    jobs:
                        - <orb-name>/<job-name>
executors:
    default:
        description: |
            This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here. If you do not require an executor, you can simply delete this directory.
        docker:
            - image: alpine:<<parameters.tag>>
        parameters:
            tag:
                default: latest
                description: |
                    Pick a specific cimg/node image variant: https://hub.docker.com/r/cimg/node/tags
                type: string
jobs:
    hello:
        description: |
            Job is responsible for greeting.
        executor: default
        parameters:
            to:
                default: World
                description: Hello to whom?
                type: string
        steps:
            - greet:
                to: << parameters.to >>
scripts: {}
version: 2.1

